[package]
name = "wasm_bindgen_helper_macros"
description = "helper macros for a couple arbitrary use cases"
version = "0.0.2"
edition = "2021"
repository = "https://github.com/SiriusAshling/wasm_bindgen_helper_macros"
license = "MIT"

[dev-dependencies]
wasm-bindgen = "0.2"
